# yaml-language-server: $schema=https://json-schema.axonivy.com/app/11.3.1/rest-clients.json
RestClients:
  NatifAI (Natif Document Capturing API):
    UUID: 6ac8b7fd-3bfa-4d47-b5d2-870c862f316c
    Url: https://api.natif.ai
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    OpenAPI:
      SpecUrl: file:///C:/Users/hdvu/Downloads/Invoice%20Extraction-openapi.json
      Namespace: ai.natif.api.client
